// Code generated by ent, DO NOT EDIT.

package runtime

import (
	"entgo.io/bug/ent/group"
	"entgo.io/bug/ent/schema"
	"entgo.io/bug/ent/todo"
	"entgo.io/bug/ent/user"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	groupMixin := schema.Group{}.Mixin()
	groupMixinHooks0 := groupMixin[0].Hooks()
	group.Hooks[0] = groupMixinHooks0[0]
	groupMixinInters0 := groupMixin[0].Interceptors()
	group.Interceptors[0] = groupMixinInters0[0]
	todoMixin := schema.Todo{}.Mixin()
	todoMixinHooks0 := todoMixin[0].Hooks()
	todo.Hooks[0] = todoMixinHooks0[0]
	todoMixinInters0 := todoMixin[0].Interceptors()
	todo.Interceptors[0] = todoMixinInters0[0]
	userMixin := schema.User{}.Mixin()
	userMixinHooks0 := userMixin[0].Hooks()
	user.Hooks[0] = userMixinHooks0[0]
	userMixinInters0 := userMixin[0].Interceptors()
	user.Interceptors[0] = userMixinInters0[0]
}

const (
	Version = "v0.11.5-0.20221208130852-6c5ffd8ea89e"           // Version of ent codegen.
	Sum     = "h1:ZpE8dOo/IT85/41p4NcSXmZUSdrn6YV/krj47j0rEoA=" // Sum of ent codegen.
)
