// Code generated by entc, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"entgo.io/bug/ent/other"
	"entgo.io/ent/dialect/sql"
)

// Other is the model entity for the Other schema.
type Other struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Other) scanValues(columns []string) ([]interface{}, error) {
	values := make([]interface{}, len(columns))
	for i := range columns {
		switch columns[i] {
		case other.FieldID:
			values[i] = new(sql.NullInt64)
		case other.FieldName:
			values[i] = new(sql.NullString)
		default:
			return nil, fmt.Errorf("unexpected column %q for type Other", columns[i])
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Other fields.
func (o *Other) assignValues(columns []string, values []interface{}) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case other.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			o.ID = int(value.Int64)
		case other.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				o.Name = value.String
			}
		}
	}
	return nil
}

// Update returns a builder for updating this Other.
// Note that you need to call Other.Unwrap() before calling this method if this Other
// was returned from a transaction, and the transaction was committed or rolled back.
func (o *Other) Update() *OtherUpdateOne {
	return (&OtherClient{config: o.config}).UpdateOne(o)
}

// Unwrap unwraps the Other entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (o *Other) Unwrap() *Other {
	tx, ok := o.config.driver.(*txDriver)
	if !ok {
		panic("ent: Other is not a transactional entity")
	}
	o.config.driver = tx.drv
	return o
}

// String implements the fmt.Stringer.
func (o *Other) String() string {
	var builder strings.Builder
	builder.WriteString("Other(")
	builder.WriteString(fmt.Sprintf("id=%v", o.ID))
	builder.WriteString(", name=")
	builder.WriteString(o.Name)
	builder.WriteByte(')')
	return builder.String()
}

// Others is a parsable slice of Other.
type Others []*Other

func (o Others) config(cfg config) {
	for _i := range o {
		o[_i].config = cfg
	}
}
