// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"time"

	"entgo.io/bug/ent/todo"
	"entgo.io/bug/ent/user"
)

func SetDeletedTimeForType(ctx context.Context, c *Client, typ string, t time.Time, ids []int) error {
	switch typ {
	case "Todo":
		return c.Todo.Update().Where(todo.IDIn(ids...)).SetDeletedTime(t).Exec(ctx)
	case "User":
		return c.User.Update().Where(user.IDIn(ids...)).SetDeletedTime(t).Exec(ctx)

	}

	return fmt.Errorf("type (%s) not found", typ)
}
